rsync -av /omega/imsis /Bills/omega/imsis
rsync -av /omega/subsidio /Bills/omega/subsidio
rsync -av /omega/save /Bills/omega/save
rsync -av /omega/devolucion /Bills/omega/devolucion
rsync -av /omega/categoria /Bills/omega/categoria
rsync -av /omega/procedencia /Bills/omega/procedencia
rsync -av /omega/seedstock /Bills/omega/seedstock
rsync -av /omega/transferencia /Bills/omega/transferencia
rsync -av /omega/spc /Bills/omega/spc
rsync -av /omega/limbo /Bills/omega/limbo
rsync -av /omega/despacho_did /Bills/omega/despacho_did
rsync -av /omega/files /Bills/omega/files
rsync -av /omega/upload /Bills/omega/upload
rsync -av /omega/upload/order /Bills/omega/upload/order
rsync -av /omega/upload/transfer /Bills/omega/upload/transfer
rsync -av /omega/upload/movimiento /Bills/omega/upload/movimiento
rsync -av /omega/upload/reingreso /Bills/omega/upload/reingreso
rsync -av /omega/upload/ajuste /Bills/omega/upload/ajuste
rsync -av /omega/upload/cambiar_codigo /Bills/omega/upload/cambiar_codigo
rsync -av /omega/files/order /Bills/omega/files/order
rsync -av /omega/files/transfer /Bills/omega/files/transfer
rsync -av /omega/files/cerrar_oc /Bills/omega/files/cerrar_oc
rsync -av /omega/files/reingreso /Bills/omega/files/reingreso
rsync -av /omega/files/cambiar_codigo /Bills/omega/files/cambiar_codigo
rsync -av /omega/upload/ptos_masivos /Bills/omega/upload/ptos_masivos
rsync -av /omega/contrato /Bills/omega/contrato
rsync -av /omega/salida /Bills/omega/salida
rsync -av /omega/cargado_precio /Bills/omega/cargado_precio
rsync -av /omega/cargado_notcredeb /Bills/omega/cargado_notcredeb
rsync -av /omega/asignacion_abogados /Bills/omega/asignacion_abogados
rsync -av /omega/ajuste_masivo /Bills/omega/ajuste_masivo
rsync -av /omega/xmlrpc /Bills/omega/xmlrpc
rsync -av /omega/rma/files/upload /Bills/omega/rma/files/upload
rsync -av /omega/reporte_recargas /Bills/omega/reporte_recargas
rsync -av /omega/reporte_nz /Bills/omega/reporte_nz
rsync -av /omega/files/devueltos_consignacion /Bills/omega/files/devueltos_consignacion
rsync -av /omega/rep_consignacion /Bills/omega/rep_consignacion
rsync -av /omega/files/cambio_consignacion /Bills/omega/files/cambio_consignacion
rsync -av /omega/files/aplausos /Bills/omega/files/aplausos
